name: Manual undeploy
on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Stage to be undeployed'
        required: true
        default: 'dev'

jobs:
  undeploy:
    name: Undeploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: echo "Stage - $STAGE"
        env:
          STAGE: ${{ inputs.stage }}